//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pvvk22cntt3lesson10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PvvAccount
    {
        public int PvvID { get; set; }
        public string PvvUsersName { get; set; }
        public string PvvPassword { get; set; }
        public string PvvFullName { get; set; }
        public string PvvEmail { get; set; }
        public string PvvPhone { get; set; }
        public Nullable<bool> PvvActive { get; set; }
    }
}
